### ISSUE TITLE
Data Fix: Great Club cannot be infused

### ISSUE THREAD

**Issue by spncr** [ThomasJClark/elden-ring-weapon-calculator#1]
Tom,
Thank you for putting this tool together, it is super useful!

As far as I know, the[ Great Club ](https://eldenring.wiki.fextralife.com/Great+Club) cannot be infused, but the weapon calculator offers it with infusions. It does upgrade with standard stones which is a bit odd.

Anyway, no urgency coming for me, mostly just wanted to let you know you are appreciated.

**Comment by ThomasJClark** [comment]
Thanks, will take a look

**Comment by ThomasJClark** [comment]
Fix is deployed: https://github.com/ThomasJClark/elden-ring-weapon-calculator/runs/10128640451

The Great Club will no longer show up if you pick affinities other than special
