### ISSUE TITLE
Keeping the tool up-to-date with Reforged

### ISSUE THREAD

**Issue by ividyon** [ThomasJClark/elden-ring-weapon-calculator#11]
Is there anything I can do to assist with ERR version updates? ERR patches very frequently, so weapon scalings will be off by small amounts pretty often.

I see you wrote that you use DSMS to get the raw data; it might be possible to get what you need directly from the files if you give me a little context.

**Comment by ividyon** [comment]
If you have enough automation in place that a PR with the new CSVs would directly result in a rebuilt app with the new values, I could post/self-approve PRs for each version, for instance.

**Comment by ThomasJClark** [comment]
Thanks, that would be much appreciated.

I just used the CSV export in DSMS to save the following param tables into `data/reforged/`:

- `AttackElementCorrectParam`
- `CalcCorrectGraph`
- `EquipParamWeapon`
- `ReinforceParamWeapon`
- `SpEffectParam` (only the rows relevant to weapon status effects)

If you're willing to help out and open a PR each time, you can rebuild the data and test the changes locally like this. I'll approve any PRs that help keep the weapon scaling up to date.

```sh
# one-time setup
nvm install && yarn install

# rebuild (run this when the CSVs change, and commit both the CSVs and the generated files in public/)
yarn rebuildWeaponData 

# test locally
yarn start
```

**Comment by ividyon** [comment]
Alright, thanks for the instructions! I sent my first PR.
