### ISSUE TITLE
Many shields missing

### ISSUE THREAD

**Issue by 2beyajay** [ThomasJClark/elden-ring-weapon-calculator#12]
Many shields are missing from the tool. Went there looking for fingerprint but noticed quite a few are not there.

**Comment by ThomasJClark** [comment]
That's strange. It might be hidden by your selections.

What options do you have selected in the checkboxes on the left? For Fingerprint to show up "Greatshield" should be checked, as well as any affinity other than "Unique".

Also, if "Effective only" is checked, anything with unmet stat requirements won't be included. Entering 48 strength or unchecking this option is necessary for Fingerprint to appear.
