### ISSUE TITLE
Insufficient stat penalty for ERR is wrong

### ISSUE THREAD

**Issue by ThomasJClark** [ThomasJClark/elden-ring-weapon-calculator#17]
In Elden Ring Reforged, the penalty for missing required stats is harsher than vanilla. I think it's around -50%, but the calculator uses the vanilla -40% penalty, so the AP shown is higher than it really is in the mod.

![image](https://user-images.githubusercontent.com/3964980/235367791-5e772d40-cb57-4ef0-bdf5-37c33d0417a0.png)

**Comment by ividyon** [comment]
@ThomasJClark `lowStatus_AtkPowDown` in PlayerCommonParam 0
