### ISSUE TITLE
ERR weapon catalysts

### ISSUE THREAD

**Issue by ividyon** [ThomasJClark/elden-ring-weapon-calculator#26]
0.9.0 introduced a new weapon type which contains daggers, halberds etc. I tried adding it, but the items would still display as their original categories. Any ideas?

PS Weapon and Dual Catalysts using those particular weapon type ids is an ERR thing, not universal, but there's seemingly no per-mod.weapon type support.

**Comment by ividyon** [comment]
```ts
const wepTypeOverrides = new Map([
  // Categorize unarmed as a fist weapon I guess
  [110000, WeaponType.FIST],
  ...(isReforged
    ? ([
        // Categorized Reforged hybrid casting tools by their melee movesets
        [1070000, WeaponType.DAGGER], // Glintstone Kris
        [2180000, WeaponType.STRAIGHT_SWORD], // Carian Knight's Sword
        [2250000, WeaponType.STRAIGHT_SWORD], // Lazuli Glintstone Sword
        [4110000, WeaponType.COLOSSAL_SWORD], // Troll Knight's Sword
        [11060000, WeaponType.HAMMER], // Varre's Bouquet
        [16100000, WeaponType.SPEAR], // Disciple's Rotten Branch
        [18100000, WeaponType.HALBERD], // Loretta's War Sickle
        [18170000, WeaponType.HALBERD], // Starcaller Spire
      ] as const)
    : []),
]);
```

Ah, I found your code where you're intentionally sorting them into existing categories. Is this a personal preference? The same seems to happen for Dual Catalysts, which are sorted into staves & seals. Is this all to avoid adding non-vanilla/per-mod weapon types to the calculator? Users would likely try to search for the actual weapon category names in the list.

P.S. the Nox Flowing Fist hack is also unnecessary, since this was just fixed.

Since you have good knowledge of what's going on with Reforged, can I assume you are on the Discord? It might make communication easier.

**Comment by ThomasJClark** [comment]
>Ah, I found your code where you're intentionally sorting them into existing categories. Is this a personal preference?

Yeah, adding an ERR-only weapon catalyst option should be possible, but I thought it would be easy to miss. If you previously saw Loretta's Sickle when selecting halberds, it might be confusing ifit doesn't show up anymore

**Comment by ThomasJClark** [comment]
>The same seems to happen for Dual Catalysts, which are sorted into staves & seals. Is this all to avoid adding non-vanilla/per-mod weapon types to the calculator? Users would likely try to search for the actual weapon category names in the list.

Dual Catalysts actually don't have this override, but the filter logic shows them if either staff or seal is selected (https://github.com/ThomasJClark/elden-ring-weapon-calculator/blob/master/src/search/filterWeapons.ts#L49)

```ts
if (
  !weaponTypes.has(weapon.weaponType) &&
  // Treat hybrid seals/staves as either category
  !(
    weapon.weaponType === WeaponType.UNIVERSAL_CATALYST &&
    (weaponTypes.has(WeaponType.SACRED_SEAL) || weaponTypes.has(WeaponType.GLINTSTONE_STAFF))
  )
) {
```

I think this behavior (implemented in a less hacky way) might also be good for ERR weapon catalysts as well. For example, selecting either "Dagger", "Glintstone Staff", or "Sacred Seal" would include Glintstone Kris. Thoughts?

>Since you have good knowledge of what's going on with Reforged, can I assume you are on the Discord? It might make communication easier.

Yep - `tom @thechewanater` on the ERR discord

**Comment by ThomasJClark** [comment]
Updated the "glinstone staff" / "sacred seal" filters to instead filter anything capable of casting sorceries or incantations respectively. I think this makes it as easy as possible to find ERR hybrid weapons and dual catalysts, but I'm open to other ideas as well
