### ISSUE TITLE
Separate links for different versions

### ISSUE THREAD

**Issue by Sunbleached022** [ThomasJClark/elden-ring-weapon-calculator#28]
It would be nice if the 3 different versions of the website (Vanilla, Reforged and Convergence) so it's easier to link to them

**Comment by ThomasJClark** [comment]
Good point, I see people getting to the calc from the ERR/convergence discords and then get confused that it's vanilla. I'll look into adding that.

**Comment by ThomasJClark** [comment]
Resolved in 5f9aecf8

Vanilla: https://eldenring.tclark.io/
Reforged: https://eldenring.tclark.io/reforged
Convergence: https://eldenring.tclark.io/convergence
