### ISSUE TITLE
[Feature Request] Calculate weapon damage output against an enemy with specific Negation/Absorption

### ISSUE THREAD

**Issue by ben-p-commits** [ThomasJClark/elden-ring-weapon-calculator#31]
Would be great if there was an additional widget whereby you could input damage negation / absorption values for physical and non physical damage types so that you could 'dry run' a weapon in a given circumstance.

Even better, you could allow custom values to be input, or you could have a fuzzy search of NPCs/bosses in the game that would let you populate the values automatically.

Use case:

> I'm playing high DEX, mid ARC and I want to kill a death bird.
> What's my best option with a strike weapon? 
> Should I go totally physical with Keen? Occult? Lightning?
> Is the 40 Lighting damage negation on the bird a dealbreaker?

If you don't have the time to work on this @ThomasJClark, I might be interested in contributing 🖖🏻

**Comment by ThomasJClark** [comment]
Thanks for the suggestion, that's a cool idea. I think it's outside of the scope of this tool, but I'd definitely be interested in checking it out if you make something for that
