### ISSUE TITLE
The "Great Stars" Great Hammer is missing!

### ISSUE THREAD

**Issue by ppblitto** [ThomasJClark/elden-ring-weapon-calculator#35]
![image](https://github.com/ThomasJClark/elden-ring-weapon-calculator/assets/57157437/16c7e09c-9ead-4b2b-a1ea-f48d96c139ad)
[Link for the weapon on the wiki](https://eldenring.fandom.com/wiki/Great_Stars)

**Comment by ThomasJClark** [comment]
You have "Effective only" checked in the top left. This option only shows weapons that you can wield with the entered stats. Try unchecking this box, or increasing the stats to the minimum for Great Stars

**Comment by ppblitto** [comment]
Omg, that was so stupid... I'm sorry to bother!

**Comment by ThomasJClark** [comment]
no problem. I guess it doesn't explain what that checkbox does very well
