### ISSUE TITLE
Rellanas Twin Blades missing?

### ISSUE THREAD

**Issue by MonsteRico** [ThomasJClark/elden-ring-weapon-calculator#37]
title

**Comment by ThomasJClark** [comment]
It's showing up for me

![image](https://github.com/ThomasJClark/elden-ring-weapon-calculator/assets/3964980/5e78bf48-e69d-4cfa-af8f-53088f26c4ea)

Make sure you have "Include DLC Weapons" checked, and it isn't hidden due to another filter (weapon type or attribute requirements)

**Comment by MonsteRico** [comment]
I either must be blind or my filters were messed up. Found it though, thanks!
