### ISSUE TITLE
Different result on mobile web and web

### ISSUE THREAD

**Issue by failsafe000** [ThomasJClark/elden-ring-weapon-calculator#38]
Using chrome on a Samsung phone and chrome on a windows PC to access. The results are different for the same stat and option selection for rivers of blood (at least). On PC it's the highest damage weapon, on mobile not in top 10.

**Comment by ThomasJClark** [comment]
Can you post a screenshot showing this? Maybe you have different stats or something entered

**Comment by failsafe000** [comment]
Mobile

**Comment by ThomasJClark** [comment]
sorry I don't see your attachment, can you try uploading it to the GH thread?
