### ISSUE TITLE
Show groups

### ISSUE THREAD

**Issue by Tom-Smith-95** [ThomasJClark/elden-ring-weapon-calculator#4]
Hello. I think it would be beneficial to add an option to group weapons by weapon type, like the "Show groups" option from https://soulsplanner.com/darksouls3/weaponatk

**Comment by ThomasJClark** [comment]
Good idea, I'll give it a look

**Comment by ThomasJClark** [comment]
Deployed: https://github.com/ThomasJClark/elden-ring-weapon-calculator/runs/12412570723

You can check the "Group weapon types" checkbox to group weapons by type, similar to the soulsplanner feature

![image](https://user-images.githubusercontent.com/3964980/228992544-375173d4-533d-4a07-b1ac-dfe4aa3a249b.png)
