### ISSUE TITLE
Total AP accumulation error for Flame Art Greataxe +25

### ISSUE THREAD

**Issue by LonelyStalker** [ThomasJClark/elden-ring-weapon-calculator#40]
Physical Attack 417
Fire Attack 506
Total 924 (Should be 923?)
It could be a problem caused by decimal accumulation.

**Comment by ThomasJClark** [comment]
It's weird, but this is actually reproducing the way the game rounds numbers. It sums up the total including decimals, but rounds everything down before displaying.

![image](https://github.com/ThomasJClark/elden-ring-weapon-calculator/assets/3964980/3c450cca-7d59-48e7-949a-3b38b768b6a0)

![image](https://github.com/ThomasJClark/elden-ring-weapon-calculator/assets/3964980/b57f5327-e412-4771-95bd-a1ec351d4242)
