### ISSUE TITLE
Poisoned Hand missing from list

### ISSUE THREAD

**Issue by ajinsoopark** [ThomasJClark/elden-ring-weapon-calculator#44]
Poisoned Hand missing from weapons list

**Comment by ThomasJClark** [comment]
It's in there - make sure you have "Include DLC weapons" checked

![image](https://github.com/user-attachments/assets/767398a6-72ef-4e2e-9bf6-d6646aa5f730)

**Comment by ajinsoopark** [comment]
The issue was the Unique option was unticked.

**Comment by ThomasJClark** [comment]
Oh yeah that would also do it. The "unique" affinity option shows weapons that can't be assigned affinities, like somber weapons

**Comment by ajinsoopark** [comment]
Changing 'Unique' to 'Somber' might be better for readability, but take that with a grain of salt
