### ISSUE TITLE
Missing weapon

### ISSUE THREAD

**Issue by Ninmenka** [ThomasJClark/elden-ring-weapon-calculator#45]
Thus calculator has been almost perfectly accurate, and incredibly helpful, but the one weapon I've found to be missing is Rellana's twin blades

**Comment by ThomasJClark** [comment]
Thanks! Rellana's Twin Blades are there - make sure you select "Include DLC Weapons" and don't have any other filters that would exclude them

![image](https://github.com/user-attachments/assets/4703b9c7-6c89-46c8-9a6e-e06d0c8642a9)
