### ISSUE TITLE
Two-handing Non-Physical Hardcap Oversight/Bug

### ISSUE THREAD

**Issue by Hazelpls** [ThomasJClark/elden-ring-weapon-calculator#47]
Hello, I've noticed that two-handing weapons with 99 strength when using a weapon that has non-physical damage which scales with strength isn't consistent with the game's.

Example, I am using a fire milady with **99 strength** and 17 dexterity, the one-handing total damage output is 663, which is consistent in the weapon calculator website and in-game. However, when I two-hand the fire milady, the website claims that it should do 700 total damage, but in the game, it shows that it deals 682 total damage.

I've researched how strength scaling with two-handing works, and though strength indeed can scale past 99, up to 148.5 with two-handing, it only affects physical damage, meaning non physical damage still hardcaps at 99, the wiki itself states: "**Note that in the rare case that magic, fire, lightning, or holy scales on strength**, the soft caps are always 20/50/80 **with a hard cap at 99, even when two-handing.**"

I've tested out this concept by **adding the two-handing 352 in physical damage** of the fire milady with the **one-handing 330 in fire damage** of the fire milady (since the hardcap for fire damage is at 99 strength, which I am at in stats). **The results of adding the two values is 682 total damage**, which is what is displayed in game.

**In short, two-handing weapons can make strength go over 99, improving physical damage, but non-physical damage will still cap at 99**, meaning the correct total damage value of two handing when the strength value goes over 99 is the addition of physical damage scaling off of the strength stat when two-handing, plus the non-physical damage scaling off 99 in the strength stat since it cannot go higher because of the hardcap.

**To easily fix this, simply keep the physical scaling as it is in the website** because it is correct, **but make it so that when non-physical damage scales off of strength, hardcap it at 99** since it cannot go higher, even when two-handing.

Thank you for your time, sincerely, an Elden Ring fan with too much time on their hands.

Wiki page with the text I've sampled: https://eldenring.wiki.fextralife.com/Strength#:~:text=Note%20that%20in%20the%20rare,are%2015%2F30%2F45.

**Comment by ThomasJClark** [comment]
Thanks for the heads up, you're absolutely right. I think the bug is essentially that the calculator doesn't clamp the min and max scaling correctly to the values specified in the `CalcCorrectGraph` param. If so, should be a quick fix

**Comment by ThomasJClark** [comment]
Fixed in 7d7dba825b50d82fcedf64182a6608e0314b08ed
