### ISSUE TITLE
Reforged File has an issue and cannot be read

### ISSUE THREAD

**Issue by Steuvan** [ThomasJClark/elden-ring-weapon-calculator#49]
![image](https://github.com/user-attachments/assets/36d49515-bf5c-4a1f-bc57-a2062faef29d)

**Comment by ThomasJClark** [comment]
Sorry, but I don't see this issue happening for me. It also looks like your screen says "v1.0.0B" instead of "v1.0.0G". Maybe try refreshing the page?
