### ISSUE TITLE
Different options for special and regular upgrades

### ISSUE THREAD

**Issue by Tom-Smith-95** [ThomasJClark/elden-ring-weapon-calculator#5]
Hello. I propose separating the regular and special upgrades such that you'd be able to compare +25 regular weapons with +5 special weapons, for example.

Here's an example of a tool that allows you to do such comparisons, although it only works for base damage: https://negator13-eldenring.azurewebsites.net/weapons

**Comment by ThomasJClark** [comment]
Interesting idea, is there a common use case for comparing different weapon levels in the same table? Typically the more upgraded weapons would be better in every way

**Comment by Tom-Smith-95** [comment]
You don't really get normal and somber stones at the same rate from the same places, so your somber and normal weapons might be mismatched. For example, assuming you thoroughly explore Liurnia, by the time you finish it, you can have a +13 normal weapon and a +4 somber. Being able to compare mismatched normal/somber upgrades would be beneficial, at least for PvE.

You can have the current weapon level selector as it is now and have a second one, for somber weapons only, that is disabled by default. If the somber level selector is set to something other than a blank value, or whatever you want to be the default, then it would take effect and the somber weapons would be shown with the upgrade of the somber selector instead of the normal one. I don't know. It's just an idea. You could also have the somber selector be a slave and change automatically as you change the master, but have the ability to change the slave independently without affecting the master.

**Comment by ThomasJClark** [comment]
Closing this - my recommendation would be to switch the weapon level back and forth when comparing different reinforcement levels. While it could be more convenient, I think the most common use case is comparing weapons of the same level and I'd like to keep it simple.
