### ISSUE TITLE
Consider adding values from some popular overhaul mods

### ISSUE THREAD

**Issue by AndriySvyryd** [ThomasJClark/elden-ring-weapon-calculator#7]
In particular, [Elden Ring Reforged](https://www.nexusmods.com/eldenring/mods/541)

**Comment by ThomasJClark** [comment]
Good idea. I have no idea how easily accessible the weapon data is for those mods, so I'll have to look into it.

**Comment by ividyon** [comment]
@ThomasJClark If you need help with figuring anything out, let me know; I work on Reforged.

**Comment by ThomasJClark** [comment]
Thanks @ividyon  will definitely let you know if I need help. I'm taking a look at the mod files to estimate the scope of this, but I think it should be totally viable to import the modified EquipParamWeapon/CalcCorrectGraph/ReinforceParamWeapon/etc. into the calculator

**Comment by ThomasJClark** [comment]
@ividyon a couple questions

1. I see Reforged changes how status buildup increases with weapon upgrade. Do you know which param table or field was changed to do this?  Is something different in the `SpEffectParam` for the status buildup effect, or is this a change to a script?
2. The regulation data has weapons with a "Reforged" affinity (e.g. "Gargoyle's Halberd [Reforged]") but there isn't a reinforce type or CalcCorrectGraph for these. Is this a placeholder for something, or an obtainable affinity?

**Comment by ividyon** [comment]
@ThomasJClark 

There is generally not much scripting in Souls for things like that, they're usually quite hardcoded. So params will hold all your answers. You can use Dsmapstudio to navigate them comfortably.

The Reforged affinity is not yet implemented and can be skipped.

**Comment by AndriySvyryd** [comment]
I'm updating the TarnishedSpreadsheet's spreadsheet https://docs.google.com/spreadsheets/d/1ki0jmMkfeNdVxd3G1WggXdXrHHVWVAClRsYtsJvmTiI/copy
It's still WIP, only the items are done so far.

**Comment by ThomasJClark** [comment]
WIP preview link: https://err.elden-ring-weapon-calculator.pages.dev/. Pick "Elden Ring Reforged" in the dropdown on the left (or in the hamburger menu on mobile).

There are still some bugs I'm aware of and more testing to be done. In particular:

- Some scaling curves aren't working, resulting in NaN attack power
- Cipher Pata has 0 attack power for some reason
- Missing icons for new affinities
- Need to actually verify that the calculations match in-game stats

But overall it seems very close to working
